#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    n = int(input().strip())
    numbers = [1,2,3,4,5,6,7,8,9,10]
for i in numbers:
    print(n, "x", i, "=", i * n)
