#!/bin/python3

import math
import os
import random
import re
import sys


def bitwiseAnd(N, K):
    max_val=0
    for A in range(1, N + 1):
        for B in range(A + 1, N + 1):
            current_val = A & B

            if current_val < K and current_val > max_val:
                max_val = current_val

    return max_val

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        count = int(first_multiple_input[0])

        lim = int(first_multiple_input[1])

        res = bitwiseAnd(count, lim)

        fptr.write(str(res) + '\n')

    fptr.close()
