#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':

    arr = []
    hourglass_sums = []


    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))
    for i in range(0,len(arr)-2):
        for j in range(0,len(arr[1])-2):
            hourglass_top = arr[i][j]+arr[i][j+1]+arr[i][j+2]
            hourglass_mid = arr[i+1][j+1]
            hourglass_bottom = arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2]
            hourglass_sum_each = hourglass_top + hourglass_mid + hourglass_bottom
            hourglass_sums.append(hourglass_sum_each)
print(max(hourglass_sums))
